steps:
- name: gcr.io/cloud-builders/mvn
  id: test
  entrypoint: mvn
  args: ['test']
- name: gcr.io/cloud-builders/mvn
  id: deploy
  args: ['deploy']
- name: gcr.io/cloud-builders/mvn
  id: containerize
  args:
  - "compile"
  - "jib:build"