steps:
- name: gcr.io/cloud-builders/mvn
  id: "unit test"
  entrypoint: mvn
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args: ['test']
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  id: "static analysis"
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login=$${SONAR_TOKEN}'
  - '-Dsonar.projectKey=kenthua_cloudbuild-ar'
  - '-Dsonar.organization=kenthua'
  - '-Dsonar.java.source=src'
  - '-Dsonar.java.binaries=target'
  secretEnv: ['SONAR_TOKEN']
- name: gcr.io/cloud-builders/mvn
  id: "push artifacts"
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args: 
  - "deploy"
  - "-Dmaven.test.skip=true"
- name: gcr.io/cloud-builders/mvn
  id: containerize
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args:
  - "compile"
  - "jib:build" 
- name: gcr.io/k8s-skaffold/skaffold:v1.35.0
  id: "skaffold deploy"
  entrypoint: /bin/sh
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  args:
  - "-c"
  - |
    export KUBECONFIG="/workspace/cgw-kubeconfig" && \
    gcloud container hub memberships get-credentials ${_CLUSTER_NAME} && \
    skaffold deploy \
    --profile abm \
    --kubeconfig /workspace/cgw-kubeconfig \
    --tag ${SHORT_SHA}
# - name: gcr.io/cloud-builders/gcloud
#   id: "k8s deploy"
#   entrypoint: /bin/sh
#   env:
#   - "PROJECT_ID=${PROJECT_ID}"
#   args:
#   - "-c"
#   - |
#     export KUBECONFIG="${pwd}/cgw-kubeconfig" && \
#     gcloud container hub memberships get-credentials ${_CLUSTER_NAME} && \
#     kubectl --kubeconfig ${pwd}/cgw-kubeconfig apply -f kubernetes-manifests/deployment.yaml
substitutions:
  _CLUSTER_NAME: cluster-1
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/SONAR_TOKEN/versions/1
    env: 'SONAR_TOKEN'
options:
  anthosCluster:
    membership: projects/${PROJECT_NUMBER}/locations/global/memberships/${_CLUSTER_NAME}