steps:
- name: gcr.io/cloud-builders/mvn
  id: "unit test"
  entrypoint: mvn
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args: ['test']
- name: gcr.io/cloud-builders/mvn
  id: "push artifacts"
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args: 
  - "deploy"
  - "-Dmaven.test.skip=true"
- name: gcr.io/cloud-builders/mvn
  id: containerize
  env:
  - "PROJECT_ID=${PROJECT_ID}"
  - "BUILD_ID=${BUILD_ID}"
  - "SHORT_SHA=${SHORT_SHA}"
  args:
  - "compile"
  - "jib:build"